version: "3"
services:
  db:
    image: postgres
    env_file:
      - .env.local
    ports:
      - 5432:5432
    networks:
      - network
  migrations:
    depends_on:
      - db
    image: migrate/migrate
    volumes:
      - ./migrations/up:/migrations/
    networks:
      - network
    command: ["-database", $POSTGRES_URL, "-path", "migrations", "up"]
  graphql:
    depends_on:
      - db
      - migrations
    image: graphile/postgraphile
    ports:
      - 5433:5433
    networks:
      - network
    command:
      [
        "--connection",
        $DATABASE_URL,
        "--port",
        "5433",
        "--schema",
        "rc4laundry",
      ]

networks:
  network:
